kind: pipeline
type: docker
name: openttd-docker

steps:
  - name: publish
    image: plugins/docker
    settings:
      repo: https://git.magnatox.com/tonymmm1/openttd-docker/src/branch/drone
      registry: https://docker.magnatox.com
      auto_tag: true
      username: 
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event: [tag]
