kind: pipeline
type: docker
name: openttd-docker

steps:
  - name: publish
    image: plugins/docker
    settings:
      repo: https://docker.magnatox.com/openttd
      registry: https://docker.magnatox.com
      username: 
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
        - $(DRONE_COMMIT_BRANCH}
