version: "3.2"
services:
  openttd:
    build: .
    image: openttd
    container_name: openttd
    ports: 
      - 3979:3979/tcp
      - 3979:3979/udp
    environment:
      - "loadgame=exit"
    volumes:
      - type: bind
        source: ./openttd
        target: /openttd
        read_only: false
    restart: always

